Adds Airflow Extension for GFW.
GlobalFishingWatch/airflow-gfw pull request #1
Opened 2019-02-26 14:27 UTC by smpiano

The process of extraction the airflow part from pipe-tools is this one
https://docs.google.com/document/d/1Vp5knesBo5l3A_Bqep7qCrflQ_a3E0OhtUVCBjct6s0/edit?usp=sharing

Related with> https://github.com/GlobalFishingWatch/GFW-Tasks/issues/968

2019-02-26 19:55 UTC, enriquetuya requested changes
@smpiano check my comments below.

2019-02-26 19:55 UTC, enriquetuya commented on CHANGES.md
> +  ## 0.0.1 - (2019-01-22)
NO need to add a tab here.

2019-02-26 19:55 UTC, enriquetuya commented on README.md
> +## Installation
@smpiano we need to change the README. There is no actual installation, so you can remove all `docker` stuff from here. You also want to add a more descriptive intro, so when reading it you know what to expect in the repo.

2019-02-27 13:28 UTC, smpiano commented on CHANGES.md
> +  ## 0.0.1 - (2019-01-22)
@enriquetuya ok, thanks!

2019-02-27 13:30 UTC, smpiano commented on README.md
> +## Installation
@enriquetuya I re-wrote README.md Explain the purposes of the package extension.

2019-02-28 14:25 UTC, enriquetuya approved these changes
@smpiano looks good to me!

2019-02-28 18:58 UTC, merged